// Base des articles de blog. Pour ajouter un article : copie un objet,
// change le "slug" (l'adresse), et remplis le contenu.
export const ARTICLES = [
  {
    slug: "carte-nfc-avis-google-nancy",
    title: "Carte NFC avis Google à Nancy : comment ça marche pour un commerçant",
    description:
      "Comment une carte NFC posée sur votre comptoir aide les commerçants de Nancy à obtenir plus d'avis Google. Fonctionnement, avantages et mise en place locale.",
    date: "2026-08-26",
    keywords: ["carte NFC avis Google Nancy", "avis Google commerçant Nancy", "carte avis Google Grand Est"],
    readingTime: 5,
    body: [
      { h2: "Pourquoi les avis Google sont décisifs pour un commerce à Nancy" },
      { p: "Quand un habitant de Nancy cherche une boulangerie, un coiffeur ou un restaurant, il tape sa recherche sur Google et compare les fiches. Celle qui a le plus d'avis récents et la meilleure note attire le clic — pas forcément le meilleur commerce, mais le mieux noté. Pour un commerçant de l'agglomération nancéienne, être invisible sur Google, c'est laisser partir des clients chez le concurrent d'à côté." },
      { p: "Le problème, c'est que même vos clients les plus satisfaits ne pensent presque jamais à laisser un avis. Ce n'est pas de la mauvaise volonté : au moment de sortir de votre boutique, ils ont autre chose en tête. C'est exactement ce point de friction qu'une carte NFC vient supprimer." },
      { h2: "Le principe de la carte NFC pour les avis Google" },
      { p: "Une carte NFC est un petit support que vous posez sur votre comptoir, à côté de votre caisse. Votre client approche son téléphone de la carte : votre page d'avis Google s'ouvre immédiatement dans son navigateur, sans aucune application à installer. Il n'a plus qu'à mettre ses étoiles et publier. L'ensemble prend une dizaine de secondes." },
      { p: "Pour les rares téléphones qui ne gèrent pas le sans-contact, un QR code imprimé sur la même carte prend le relais. Ainsi, absolument tous vos clients peuvent laisser un avis, quel que soit leur téléphone." },
      { h2: "Ce qui distingue BoostRepu d'une simple carte" },
      { p: "La plupart des cartes vendues en ligne se contentent de rediriger vers votre page Google. Elles ne vous disent jamais si elles servent à quelque chose. BoostRepu va plus loin : chaque scan est compté, et vous voyez dans un tableau de bord combien de fois votre carte a été utilisée et combien d'avis elle a réellement générés. Vous savez enfin si vos efforts portent leurs fruits." },
      { p: "L'outil inclut aussi un assistant qui rédige vos réponses aux avis et transforme vos meilleurs commentaires en visuels prêts à publier sur les réseaux sociaux — deux tâches chronophages que la plupart des commerçants n'ont jamais le temps de faire." },
      { h2: "Une solution locale, installée sur place" },
      { p: "BoostRepu est basé à Nancy et accompagne les commerçants de toute l'agglomération : Vandœuvre-lès-Nancy, Laxou, Maxéville, Villers-lès-Nancy, Saint-Max et le reste du Grand Est. Contrairement à un service en ligne anonyme, la carte est configurée à votre nom et installée directement dans votre commerce, avec un accompagnement humain." },
      { cta: "Vous tenez un commerce à Nancy ou dans le Grand Est ? Contactez-nous pour une démonstration." },
    ],
  },
  {
    slug: "comment-obtenir-plus-avis-google-commercant",
    title: "Comment obtenir plus d'avis Google quand on est commerçant",
    description:
      "7 méthodes concrètes et autorisées pour obtenir davantage d'avis Google sur votre fiche d'établissement, sans enfreindre les règles de Google.",
    date: "2026-08-26",
    keywords: ["obtenir plus d'avis Google", "améliorer ses avis Google", "plus d'avis Google commerçant"],
    readingTime: 6,
    body: [
      { h2: "Pourquoi le volume et la fraîcheur des avis comptent" },
      { p: "Google ne se contente pas de regarder votre note moyenne. L'algorithme valorise les fiches qui reçoivent des avis réguliers et récents : une fiche vivante remonte dans les résultats locaux, une fiche figée décroche, même avec une excellente note. L'objectif n'est donc pas seulement d'avoir de bons avis, mais d'en recevoir continuellement." },
      { h2: "1. Demandez au bon moment" },
      { p: "Le meilleur moment pour solliciter un avis, c'est juste après une expérience positive : au moment de payer, quand le client vous remercie, quand il repart satisfait. Attendre le lendemain par e-mail divise vos chances par dix." },
      { h2: "2. Supprimez la friction avec une carte NFC ou un QR code" },
      { p: "Plus le geste est simple, plus vous obtenez d'avis. Une carte NFC posée sur le comptoir permet au client d'accéder à votre page d'avis en approchant son téléphone, sans chercher votre fiche ni se connecter. C'est la méthode qui convertit le mieux, parce qu'elle capte l'intention au moment exact où elle existe." },
      { h2: "3. Répondez à tous les avis, même les négatifs" },
      { p: "Répondre à vos avis envoie deux signaux : à Google, que votre fiche est active ; à vos futurs clients, que vous êtes attentif. Un avis négatif auquel vous répondez calmement et professionnellement fait souvent meilleure impression que dix avis cinq étoiles sans réponse." },
      { h2: "4. Formez votre équipe" },
      { p: "Vos employés sont en première ligne. Un simple « n'hésitez pas à nous laisser un avis, ça nous aide beaucoup » prononcé au bon moment multiplie les retours. Encore faut-il leur donner un outil simple à présenter au client." },
      { h2: "5. Ne trichez jamais" },
      { p: "N'achetez pas de faux avis et ne filtrez pas vos clients pour n'envoyer que les plus satisfaits vers Google. Ces pratiques sont interdites et peuvent entraîner la suppression pure et simple de votre fiche. Des années d'avis peuvent disparaître d'un coup. La seule stratégie durable est de faciliter le dépôt d'avis authentiques." },
      { h2: "6. Suivez vos résultats" },
      { p: "Sans mesure, vous avancez à l'aveugle. Savoir combien de personnes ont scanné votre carte et combien d'avis en ont résulté vous permet d'ajuster : déplacer la carte, changer votre phrase de sollicitation, choisir un meilleur moment. C'est ce suivi qui transforme une intuition en méthode." },
      { h2: "7. Inscrivez-vous dans la durée" },
      { p: "Obtenir des avis n'est pas une opération ponctuelle mais une habitude. Les commerces qui réussissent sont ceux qui ont intégré la demande d'avis dans leur routine quotidienne, avec un outil qui rend le geste automatique." },
      { cta: "BoostRepu réunit ces méthodes dans un seul outil, avec une carte NFC et un tableau de bord de suivi. Demandez une démonstration." },
    ],
  },
  {
    slug: "carte-nfc-ou-qr-code-avis-google",
    title: "Carte NFC ou QR code pour ses avis Google : que choisir ?",
    description:
      "Comparatif entre la carte NFC et le QR code pour collecter des avis Google. Avantages, limites et pourquoi les deux sont complémentaires.",
    date: "2026-08-26",
    keywords: ["carte NFC ou QR code avis", "QR code avis Google", "carte NFC avis Google"],
    readingTime: 4,
    body: [
      { h2: "Deux technologies pour le même objectif" },
      { p: "La carte NFC et le QR code visent la même chose : envoyer votre client vers votre page d'avis Google le plus simplement possible. Mais ils ne fonctionnent pas de la même façon, et l'un n'exclut pas l'autre." },
      { h2: "Le QR code : universel mais avec une étape de plus" },
      { p: "Le QR code fonctionne sur tous les téléphones équipés d'un appareil photo, soit la totalité des smartphones actuels. Son inconvénient : le client doit ouvrir son appareil photo, viser le code, attendre la reconnaissance, puis toucher la notification. Quelques secondes de plus, et surtout plusieurs occasions d'abandonner en route." },
      { h2: "La carte NFC : plus fluide, mais pas sur tous les téléphones" },
      { p: "Avec le NFC, le client approche simplement son téléphone de la carte et la page s'ouvre. Aucun geste intermédiaire. C'est l'expérience la plus fluide, et celle qui convertit le mieux. La limite : quelques téléphones anciens ou d'entrée de gamme ne sont pas équipés de puce NFC, et certains l'ont désactivée dans leurs réglages." },
      { h2: "La vraie réponse : les deux sur le même support" },
      { p: "Opposer les deux est une fausse question. La meilleure solution combine une puce NFC pour la majorité des clients et un QR code imprimé sur la même carte pour les autres. Ainsi, personne ne passe à côté, quel que soit son téléphone." },
      { h2: "Ce qui compte vraiment : ce qui se passe après le scan" },
      { p: "Que votre client scanne en NFC ou en QR code, la vraie différence se joue après. Un support basique se contente de rediriger. BoostRepu compte chaque scan, mesure combien d'avis en résultent, et vous aide à répondre et à exploiter ces avis. C'est là que se trouve la valeur, pas dans le choix de la technologie." },
      { cta: "La carte BoostRepu combine NFC et QR code, avec un tableau de bord complet. Contactez-nous." },
    ],
  },
  {
    slug: "avis-google-restaurant-nancy",
    title: "Avis Google pour un restaurant à Nancy : le guide complet",
    description:
      "Pourquoi les avis Google font le plein (ou le vide) dans votre salle, et comment un restaurant de Nancy peut en obtenir davantage simplement, sans y passer ses soirées.",
    date: "2026-09-03",
    keywords: ["avis Google restaurant", "avis Google restaurant Nancy", "plus d'avis restaurant", "carte NFC restaurant"],
    readingTime: 6,
    body: [
      { h2: "Le premier serveur de votre restaurant, c'est Google" },
      { p: "Avant même de pousser la porte de votre établissement, un client potentiel a déjà consulté votre fiche Google. Il a regardé votre note, lu deux ou trois avis récents, jeté un œil aux photos. En quelques secondes, il décide s'il réserve chez vous ou chez le restaurant d'à côté. À Nancy, où la concurrence est dense entre la place Stanislas, la rue des Maréchaux et le centre-ville, cette première impression numérique pèse autant que votre carte." },
      { p: "Un restaurant excellent avec 40 avis passe souvent après un restaurant correct avec 300 avis, simplement parce que Google met en avant les fiches actives et abondamment commentées. Ce n'est pas juste, mais c'est ainsi que fonctionne la recherche locale." },
      { h2: "Pourquoi vos clients satisfaits ne laissent pas d'avis" },
      { p: "Vos clients repartent contents, vous le voyez à leur sourire et à leurs remerciements. Mais une fois dehors, ils passent à autre chose. Laisser un avis suppose de retrouver votre fiche, de se connecter à son compte Google, de rédiger un texte : trop d'étapes pour un geste spontané. Le résultat, c'est que seuls les clients mécontents, eux très motivés, prennent le temps d'écrire. Votre note s'en trouve tirée vers le bas alors que la majorité de vos clients sont ravis." },
      { h2: "Capter l'avis au bon moment : à table ou à l'addition" },
      { p: "Le meilleur moment pour obtenir un avis, c'est quand le plaisir est encore frais : à la fin du repas, au moment de régler. C'est là qu'une carte posée sur la table ou présentée avec l'addition fait la différence. Le client approche son téléphone, votre page d'avis s'ouvre, il met ses étoiles avant même d'avoir quitté sa chaise. Pas d'application, pas de recherche : le geste prend dix secondes, pendant qu'il a encore le sourire du dessert." },
      { p: "Pour les téléphones qui ne gèrent pas le sans-contact, un QR code sur la même carte permet le même résultat. Aucun client n'est laissé de côté, quel que soit son appareil." },
      { h2: "Répondre aux avis : un réflexe qui rapporte" },
      { p: "Un restaurateur qui répond à ses avis, positifs comme négatifs, envoie un signal fort à ses futurs clients : ici, on est attentif. Un avis négatif traité avec calme et professionnalisme rassure souvent plus que dix avis dithyrambiques. Le problème, c'est le temps : après un service, personne n'a l'énergie de rédiger des réponses. Un assistant qui les prépare pour vous, à personnaliser en un clic, change tout." },
      { h2: "Mesurer ce qui marche, plutôt que deviner" },
      { p: "Combien de clients ont scanné votre carte ce mois-ci ? Combien d'avis en sont réellement sortis ? Sans mesure, vous avancez à l'aveugle. Savoir que votre carte a été scannée 60 fois pour 15 avis vous dit quelque chose de concret : où la placer, quoi dire au client, à quel moment. C'est la différence entre espérer des avis et piloter sa réputation." },
      { h2: "Une solution pensée pour les restaurants de Nancy" },
      { p: "BoostRepu accompagne les restaurateurs de Nancy et de son agglomération — du centre-ville à Vandœuvre, Laxou ou Villers-lès-Nancy — avec une carte configurée à votre nom, installée sur place, et un tableau de bord qui suit vos résultats. Vous vous concentrez sur votre cuisine et votre salle ; la collecte d'avis, elle, devient automatique." },
      { cta: "Vous tenez un restaurant à Nancy ou dans le Grand Est ? Contactez-nous pour une démonstration." },
    ],
  },
  {
    slug: "repondre-avis-negatif-google",
    title: "Comment répondre à un avis négatif Google (avec exemples)",
    description:
      "Un avis négatif n'est pas une catastrophe, c'est une occasion. Méthode en 4 étapes et exemples de réponses pour transformer une critique en preuve de sérieux.",
    date: "2026-09-03",
    keywords: ["répondre avis négatif Google", "réponse avis négatif", "gérer avis négatif", "avis 1 étoile Google"],
    readingTime: 5,
    body: [
      { h2: "Un avis négatif se lit plus qu'il ne se subit" },
      { p: "Recevoir un avis à une étoile serre le ventre, surtout quand on a mis du cœur dans son commerce. Mais avant de le vivre comme une injustice, changez de perspective : cet avis, et surtout votre réponse, seront lus par des dizaines de futurs clients. Ce n'est pas une conversation avec le mécontent, c'est une démonstration publique de la façon dont vous gérez les problèmes. Bien traité, un avis négatif rassure plus qu'il n'inquiète." },
      { h2: "Ce qu'il ne faut jamais faire" },
      { p: "Ne répondez jamais à chaud, sur la défensive ou avec ironie. Ne contestez pas frontalement la version du client, même si elle vous semble exagérée : les lecteurs prendront systématiquement le parti de celui qui reste calme. Et ne demandez jamais à Google de supprimer un avis simplement parce qu'il est négatif — cela ne fonctionne que pour les avis qui enfreignent réellement les règles (propos haineux, faux avis manifeste)." },
      { h2: "La méthode en 4 étapes" },
      { p: "1. Remerciez pour le retour, sincèrement et sans ironie. 2. Reconnaissez le point précis qui a posé problème, sans vous cacher derrière des excuses générales. 3. Expliquez ce que vous mettez en place pour que cela ne se reproduise pas. 4. Proposez de reprendre contact en privé pour régler la situation. Ces quatre temps, en trois ou quatre phrases, suffisent à transformer une critique en preuve de professionnalisme." },
      { h2: "Exemple : temps d'attente trop long" },
      { p: "« Bonjour, merci d'avoir pris le temps de nous faire ce retour, et désolé pour l'attente que vous avez subie. Vous avez raison, ce jour-là nous étions en sous-effectif, ce qui n'excuse pas le désagrément. Nous avons depuis revu notre organisation aux heures de pointe. N'hésitez pas à revenir vers nous en message privé, nous aimerions vous accueillir à nouveau dans de meilleures conditions. »" },
      { h2: "Exemple : problème de qualité" },
      { p: "« Bonjour, merci pour votre message, et navré que votre expérience n'ait pas été à la hauteur. Ce que vous décrivez ne correspond pas à ce que nous voulons offrir. Nous avons échangé avec l'équipe pour éviter que cela se reproduise. Contactez-nous directement, nous tenons à nous rattraper. »" },
      { h2: "Répondre vite, sans y passer vos soirées" },
      { p: "La difficulté n'est pas de savoir quoi écrire, c'est de trouver le temps de le faire, avis après avis. C'est précisément là qu'un assistant qui prépare une réponse personnalisée en un clic devient précieux : vous relisez, vous ajustez d'un mot, vous publiez. Dix secondes au lieu de dix minutes, et plus aucun avis ne reste sans réponse — ce que Google, justement, valorise pour votre positionnement." },
      { cta: "BoostRepu génère vos réponses aux avis en un clic, personnalisées à votre commerce. Contactez-nous pour une démonstration." },
    ],
  },
];

export function getArticle(slug) {
  return ARTICLES.find((a) => a.slug === slug) || null;
}
